### ISSUE TITLE
Github Badges

### ISSUE THREAD

**Issue by dkoeni** [swissfintechinnovations/.github#19]
- [shields.io](https://shields.io/)

**Comment by svenbiellmann** [comment]
Ich könnte mir noch vorstellen, die Major Version der API als separaten Badge darzustellen. Im Release Badge ist die Major Version zwar enthalten aber so würde man auf einen Blick sehen, welche Major Version die aktuelle ist. Zumal die Major Version ja auch ein Bestandteil der URI ist.
